server:
  port: 8783

spring:
  datasource:
    url: jdbc:mysql://localhost:3309/crud_demo?useUnicode=true&characterEncoding=utf8
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456

mybatis:
  mapper-locations:
    - classpath:mappers/*.xml

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} %L %clr(:){faint} %m%n"
  level:
    root: INFO